In [1]:
from time import perf_counter as time

import torch
import numpy as np

In [2]:
def timeit(func):
    def wrapper(*args, **kwargs):
        t0 = time()
        value = func(*args, **kwargs)
        t1 = time()
        print(f"{t1 - t0:.2f} seconds")
        return value
    return wrapper

In [3]:
n = 1000000
a = np.arange(n).reshape(-1, 2).astype("float")
print(a[:3])

[[0. 1.]
 [2. 3.]
 [4. 5.]]


In [6]:
def func_1(x):
    return x[0]**2 + x[1]**2

@timeit
def func_2(x):
    return x[:, 0]**2 + x[:, 1]**2

@timeit
def func_3(x):
    return np.array([func_1(x[i]) for i in range(len(x))])

In [8]:
func_3(a)

0.13 seconds


array([1.000000e+00, 1.300000e+01, 4.100000e+01, ..., 1.999978e+12,
       1.999986e+12, 1.999994e+12])

In [23]:
func_1(np.array([1.0, 2.0]))

IndexError: invalid index to scalar variable.

In [21]:
a[1]

array([2., 3.])

In [11]:
another_way()

0.00 seconds


array([1.000000e+00, 1.300000e+01, 4.100000e+01, ..., 1.999978e+12,
       1.999986e+12, 1.999994e+12])

In [12]:
yet_another_way()

IndexError: invalid index to scalar variable.